### ISSUE TITLE
Review required fields for registering workflows

### ISSUE THREAD

**Issue by simleo** [crs4/life_monitor#26]
The `Workflow` API schema has `uuid`, `version` and `roc_link` as required properties, while `name` is listed as optional (both in the current master branch and in #20). However (focusing on POST calls):

* The absence of `name` is actually not handled and leads to a `KeyError` in the `workflows_post` implementation.
* It's weird to require the API user to forge a uuid for the workflow and to handle the version. Both fields should be handled by the service.
* The name, on the other hand, seems like something we want the user to specify (unless we want to set it to `"Workflow-<UUID>"` or something)

I would change `name` to be required and `uuid` and `version` to be read-only properties.

**Comment by ilveroluca** [comment]
I can comment on the uuid requirement and the name.  The mandatory uuid argument came from the idea that the workflow being tested will have been given a universal id from another service, such as the WorkflowHub.  From this perspective, LM isn't acting as a workflow registry so it expects the workflow to be already registered somewhere else, and thus have a UUID.

If this doesn't seem reasonable, we can discuss making the uuid optional, so that if it isn't provided by the user it will be generated and returned by LM.

The name is optional for the same reason:  LM isn't a registry so we figured a user could rely on some other service to store such metadata.

Perhaps this approach is too simplistic though and we should be able to collect a bit more metadata about the workflow; at the very very least, the service where that uuid came from.

**Comment by simleo** [comment]
@ilveroluca OK, I see your point. Since LM is not a registry, name, uuid and version are essentially external references, useful to the workflow poster to retrieve testing information from LM. Perhaps it's just a matter of expanding the docs to make this clearer. Then maybe it's better to leave things as they are, apart from the fact that I'd still make `name` required, since it plays an analogous role to the other fields.

**Comment by simleo** [comment]
- [x] Missing name problem fixed in #165
- [x] uuid is not required anymore, the workflow's id in the source registry is
- [ ] the version we require is, again, that of the workflow in the source registry. However, we should explain this in the docs and fix #171

**Comment by ilveroluca** [comment]
Done.
